id: 608af1b9a8534b8396275454052a972f
title: Toh_225-Taking_Refuge_in_the_Three_Jewels-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-063-006
  eft-text-version: 1.0.2 2020
